apiVersion: v1
kind: Service
metadata:
  name: {{ template "demo-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    
spec:
  type: NodePort
  ports:
    - nodePort: {{.Values.Demo.Service.NodePort}}
      port: 5555
      targetPort: 5555
  selector:
    component: {{ template "demo-fullname" . }}
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "demo-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: {{ template "demo-fullname" . }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: {{ template "demo-fullname" . }}
    spec:
      containers:
        - name: {{ template "demo-fullname" . }}
          image: "{{.Values.Demo.Image}}:{{.Values.Demo.ImageTag}}"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/iguazio/demo/config
              name: config-volume
          command: ["/bin/bash"]
          args:
            - -x
            - /etc/iguazio/demo/config/startup.sh
          ports:
            - containerPort: 5555
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "demo-fullname" . }}
